version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  browserForTesting: circleci/browser-tools@1.2.4


jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
        node-version: '16.14.2'
      - run: node --version
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - browserForTesting/install-chrome
      - run:
          name: install node modules and test frontend
          command: |
            npm run frontend:test
      - run:
          name: build frontend
          command: |
            npm run frontend:build
      - run:
          name: install node modules and test backend
          command: |
            npm run backend:test            
      - run:
          name: build backend
          command: |
            npm run backend:build
      - run:
          name: deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: deploy backend
          command: |
            npm run backend:deploy                        
            

workflows:
  main:                    
    jobs:
      - build:  
          filters:
            branches:
               only:                
                  - main