version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
        node-version: '16.14.2'
      - run: node --version
      - run:
          name: build frontend
          command: |
            npm run frontend:build
      - run:
          name: build backend
          command: |
            npm run backend:build