orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.1.0


jobs:
  build:
        node-version: '16.14.2'
      - run: node --version
      - aws-cli/setup
      - run:
          name: build frontend
          command: |
            npm run frontend:build
      - run:
          name: build backend
          command: |
            npm run backend:build
 
       